[package]
name = "raydium-clmm-client"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
anchor-lang = { workspace = true }
metrics = { workspace = true }
mtm-chain = { workspace = true }
raydium-clmm-interface = { git = "https://github.com/raydium-io/raydium-clmm", rev = "ed7c84a54ced59c55981780546adb0b4583dcf85", package = "raydium-clmm", features = ["no-entrypoint", "client"] }
rust_decimal = { workspace = true, features = ["maths"] }
solana-account = { workspace = true }
solana-commitment-config = { workspace = true }
solana-instruction = { workspace = true }
solana-keypair = { workspace = true }
solana-pubkey = { workspace = true }
solana-signature = { workspace = true }
solana-signer = { workspace = true }
spl-associated-token-account = { workspace = true }
spl-memo = { workspace = true }
spl-token = { workspace = true }
spl-token-2022 = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }

[lints]
workspace = true
